version: "2"
run:
  tests: false
linters:
  disable:
    - staticcheck
  enable:
    - bodyclose
    - goconst
    - gocritic
    - gocyclo
    - goprintffuncname
    - gosec
    - lll
    - misspell
    - nakedret
    - nlreturn
    - nolintlint
    - revive
    - rowserrcheck
    - staticcheck
    - unconvert
    - unparam
  settings:
    gocritic:
      disabled-checks:
        - hugeParam
      enabled-tags:
        - performance
        - style
        - experimental
    gosec:
      excludes:
        - G204
        - G306
    lll:
      line-length: 140
    revive:
      rules:
        - name: var-naming
          disabled: true
    staticcheck:
      checks:
        - -ST1003
        - -ST1016
        - -ST1020
        - -ST1021
        - -ST1022
        - all
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - .*easyjson\.go$
      - allure
      - mocks
      - third_party$
      - builtin$
      - examples$
      - examples/.*
formatters:
  enable:
    - gci
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/lamoda/gonkey)
      custom-order: false
      no-lex-order: false
  exclusions:
    generated: lax
    paths:
      - .*easyjson\.go$
      - allure
      - mocks
      - third_party$
      - builtin$
      - examples$
