linters:
  disable-all: true
  enable:
    - bodyclose
    - deadcode
    - errcheck
    - gocyclo
    - gosimple
    - govet
    - makezero
    - misspell
    - structcheck
    - typecheck
    - unparam
    - unused
    - varcheck
